### ISSUE TITLE
Camera.app crashes after 3 seconds

### ISSUE THREAD

**Issue by Adryd** [evilGoldfish/Live-Photos-Enabler#2]
Running 9.0.2 on iPod 5th generation. (Latest commit)

Detailed description:
When I open the Photos app the first second camera runs fine but after that it freezes and then the screen goes black, arround thirty seconds later the app crashes.

**Comment by swapvaishu** [comment]
Running 9.0.2 on iPhone 5s

Description:
When I open default camera application, screen is getting freeze and then if I try to take photo, the app is getting crashed after around 5 seconds.

**Comment by Adryd** [comment]
i have done further reasearch and this is because the tweak requires 64 bit archetecthure
